//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agency()
        {
            this.agency_debt = new HashSet<agency_debt>();
            this.sale_order = new HashSet<sale_order>();
        }
        [Display(Name = "Mã đại lý")]
        public int agency_id { get; set; }
        [Display(Name = "Tên đại lý")]
        public string agency_name { get; set; }
        [Display(Name = "Địa chỉ")]
        public string agency_address { get; set; }
        [Display(Name = "SĐT")]
        public string agency_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agency_debt> agency_debt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_order> sale_order { get; set; }
    }
}
