//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.agency_debt_item = new HashSet<agency_debt_item>();
            this.purchase_order_item = new HashSet<purchase_order_item>();
            this.purchase_payment_item = new HashSet<purchase_payment_item>();
            this.sale_order_item = new HashSet<sale_order_item>();
            this.sale_payment_item = new HashSet<sale_payment_item>();
            this.stores = new HashSet<store>();
            this.supplier_debt_item = new HashSet<supplier_debt_item>();
        }
        [Display (Name ="Mã sách")]
        public int book_id { get; set; }
        [Display(Name = "Tên sách")]
        public string book_name { get; set; }
        [Display(Name = "Nhà xuất bản")]
        public int fk_supplier { get; set; }
        [Display(Name = "Tỉ giá")]
        public Nullable<int> book_stock { get; set; }
        [Display(Name = "Giá bán")]
        public Nullable<decimal> book_seling_price { get; set; }
        [Display(Name = "Giá nhập")]
        public Nullable<decimal> book_purchase_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agency_debt_item> agency_debt_item { get; set; }
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order_item> purchase_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_payment_item> purchase_payment_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_order_item> sale_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_payment_item> sale_payment_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<store> stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_debt_item> supplier_debt_item { get; set; }
    }
}
