//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ql_sachEntities : DbContext
    {
        public ql_sachEntities()
            : base("name=ql_sachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agency> agencies { get; set; }
        public virtual DbSet<agency_debt> agency_debt { get; set; }
        public virtual DbSet<agency_debt_item> agency_debt_item { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<purchase_order> purchase_order { get; set; }
        public virtual DbSet<purchase_order_item> purchase_order_item { get; set; }
        public virtual DbSet<purchase_payment> purchase_payment { get; set; }
        public virtual DbSet<purchase_payment_item> purchase_payment_item { get; set; }
        public virtual DbSet<sale_order> sale_order { get; set; }
        public virtual DbSet<sale_order_item> sale_order_item { get; set; }
        public virtual DbSet<sale_payment> sale_payment { get; set; }
        public virtual DbSet<sale_payment_item> sale_payment_item { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supplier_debt> supplier_debt { get; set; }
        public virtual DbSet<supplier_debt_item> supplier_debt_item { get; set; }
    }
}
