//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order_item
    {
        public int purchase_order_item_id { get; set; }
        public int fk_purchase_order { get; set; }
        public int fk_book { get; set; }
        public Nullable<decimal> purchase_order_item_price { get; set; }
        public Nullable<int> purchase_order_item_quantity { get; set; }
        public Nullable<decimal> purchase_order_money { get; set; }
    
        public virtual book book { get; set; }
        public virtual purchase_order purchase_order { get; set; }
    }
}
