//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_payment()
        {
            this.purchase_payment_item = new HashSet<purchase_payment_item>();
        }
    
        public int purchase_payment_id { get; set; }
        public int fk_purchase_order { get; set; }
        public Nullable<decimal> purchase_payment_money_pay { get; set; }
        public Nullable<decimal> purchase_payment_debt { get; set; }
        public Nullable<System.DateTime> purchase_payment_time { get; set; }
    
        public virtual purchase_order purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_payment_item> purchase_payment_item { get; set; }
    }
}
