//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_order()
        {
            this.purchase_order_item = new HashSet<purchase_order_item>();
            this.purchase_payment = new HashSet<purchase_payment>();
        }
    
        public int purchase_order_id { get; set; }
        public int fk_supplier { get; set; }
        public Nullable<System.DateTime> purchase_order_created_at { get; set; }
        public Nullable<decimal> purchase_order_total_money { get; set; }
        public string purchase_order_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order_item> purchase_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_payment> purchase_payment { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
