//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sale_payment()
        {
            this.sale_payment_item = new HashSet<sale_payment_item>();
        }
    
        public int sale_payment_id { get; set; }
        public int fk_sale_order { get; set; }
        public Nullable<decimal> sale_payment_money_pay { get; set; }
        public Nullable<decimal> sale_payment_debt { get; set; }
        public Nullable<System.DateTime> sale_payment_time { get; set; }
    
        public virtual sale_order sale_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_payment_item> sale_payment_item { get; set; }
    }
}
