//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sale_order_item
    {
        [Display(Name = "Mã")]
        public int sale_order_item_id { get; set; }
        [Display(Name = "Mã phiếu xuất")]
        public int fk_sale_order { get; set; }
        [Display(Name = "Sách")]
        public int fk_book { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<decimal> sale_order_item_price { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> sale_order_item_quantity { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> sale_order_money { get; set; }
    
        public virtual book book { get; set; }
        public virtual sale_order sale_order { get; set; }
    }
}
