//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_payment_item
    {
        public int sale_payment_item_id { get; set; }
        public int fk_sale_payment { get; set; }
        public int fk_book { get; set; }
        public Nullable<int> sale_payment_item_quantity { get; set; }
        public Nullable<decimal> sale_payment_item_price { get; set; }
        public Nullable<decimal> sale_payment_item_money { get; set; }
    
        public virtual book book { get; set; }
        public virtual sale_payment sale_payment { get; set; }
    }
}
