//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sale_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sale_order()
        {
            this.sale_order_item = new HashSet<sale_order_item>();
            this.sale_payment = new HashSet<sale_payment>();
        }
        [Display(Name = "Mã phiếu xuất")]

        public int sale_order_id { get; set; }
        [Display(Name = "Mã đại lý")]
        public int fk_agency { get; set; }
        [Display(Name = "Ngày tạo phiếu")]
        public Nullable<System.DateTime> sale_order_created_at { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<decimal> sale_order_total_money { get; set; }
        [Display(Name = "Tình trạng")]
        public string sale_order_status { get; set; }
    
        public virtual agency agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_order_item> sale_order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_payment> sale_payment { get; set; }
    }
}
