//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public int store_id { get; set; }
        public int fk_book { get; set; }
        public Nullable<int> store_quantity { get; set; }
        public Nullable<decimal> store_seling_price { get; set; }
        public Nullable<decimal> store_purchase_price { get; set; }
        public Nullable<System.DateTime> store_time { get; set; }
    
        public virtual book book { get; set; }
    }
}
