//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_debt_item
    {
        public int supplier_debt_item_id { get; set; }
        public int fk_supplier_debt { get; set; }
        public int fk_book { get; set; }
        public Nullable<int> supplier_debt_item_quantity { get; set; }
        public Nullable<decimal> supplier_debt_item_money { get; set; }
    
        public virtual book book { get; set; }
        public virtual supplier_debt supplier_debt { get; set; }
    }
}
