//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_debt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier_debt()
        {
            this.supplier_debt_item = new HashSet<supplier_debt_item>();
        }
    
        public int supplier_debt_id { get; set; }
        public int fk_supplier { get; set; }
        public Nullable<decimal> supplier_debt_total_money { get; set; }
        public Nullable<System.DateTime> supplier_debt_time { get; set; }
    
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_debt_item> supplier_debt_item { get; set; }
    }
}
